Repository no-nangbie/frontend, pull requests merged in 2024-09, with the labels that each got.

#5 feat:#4 Login 화면 구성 및 Resources 추가
  package-lock.json
  package.json
  src/pages/login/Login.jsx
  src/resources/icon/board.png
  src/resources/icon/board_fix.png
  src/resources/icon/board_minus.png
  src/resources/icon/board_onclick.png
  src/resources/icon/board_plus.png
  src/resources/icon/bottom_bar.png
  src/resources/icon/bottom_bar_disable.png
  src/resources/icon/bottom_bar_test.png
  src/resources/icon/circle-microphone_10742235.png
  src/resources/icon/circle-microphone_onclick.png
  src/resources/icon/dot-pending_15354826.png
  src/resources/icon/fish_5069012.png
  src/resources/icon/heart.png
  src/resources/icon/heart_red.png
  src/resources/icon/heart_red_FillIn.png
  src/resources/icon/menu.png
  src/resources/icon/menu_minus.png
  src/resources/icon/menu_onclick.png
  src/resources/icon/menu_plus.png
  src/resources/icon/recipe.png
  src/resources/icon/recipe_onclick.png
  src/resources/icon/refrigerator.png
  src/resources/icon/refrigerator_onclick.png
  src/resources/icon/salad.png
  src/resources/icon/salt-pepper_6349779.png
  src/resources/icon/search_3917754.png
  src/resources/icon/steak_6349808.png
  src/resources/icon/stopwatch_3914496.png
  src/resources/icon/user_3917559.png
Labels: enhancement

#6 feat:#2 Menu, Recipe, Board Routing
  src/App.js
  src/pages/board/Board.jsx
  src/pages/menu/Menu.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#8 feat:#7 Layout header&Footer Nav 구현
  src/App.js
  src/layout/Layout.jsx
  src/pages/home/Home.jsx
Labels: enhancement

#10 feat:#9 Fridge design 80%
  package-lock.json
  package.json
  src/App.js
  src/layout/Layout.jsx
  src/pages/fridge/Fridge.jsx
  src/pages/home/Home.jsx
  src/resources/icon/search_white.png
Labels: enhancement

#12 feat:#11 Recipe Design
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#13 feat: #9 디자인
  src/pages/fridge/Fridge.jsx
Labels: enhancement

#15 feat:#14 Board Design
  src/pages/board/Board.jsx
Labels: enhancement

#17 feat:#16 Recipe Details Design
  src/App.js
  src/layout/Layout.jsx
  src/pages/board/Board.jsx
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
  src/pages/recipe/RecipeDetails.jsx
  src/resources/icon/cook.png
  src/resources/icon/difficulty_1.png
  src/resources/icon/difficulty_2.png
  src/resources/icon/difficulty_3.png
  src/resources/icon/etc.png
  src/resources/icon/fish.png
  src/resources/icon/microphone.png
  src/resources/icon/microphone_onclick.png
  src/resources/icon/salt-pepper.png
  src/resources/icon/steak.png
  src/resources/icon/timer.png
  src/resources/icon/user.png
  src/resources/sample/menu_1.png
  src/resources/sample/menu_2.png
Labels: enhancement

#18 feat:#7 Layout Footer Image And Header Image added
  src/layout/Layout.jsx
  src/pages/board/Board.jsx
  src/pages/login/Login.jsx
  src/pages/recipe/Recipe.jsx
  src/pages/recipe/RecipeDetails.jsx
  src/resources/icon/board.png
  src/resources/icon/board_on.png
  src/resources/icon/fridge.png
  src/resources/icon/fridge_on.png
  src/resources/icon/menu.png
  src/resources/icon/menu_on.png
  src/resources/icon/recipe.png
  src/resources/icon/recipe_on.png
  src/resources/icon/refrigerator.png
Labels: enhancement

#19 feat:#2 App Routing Add
  src/App.js
  src/layout/Layout.jsx
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeDelete.jsx
  src/pages/login/signup.jsx
  src/pages/recipe/RecipeEdit.jsx
  src/pages/recipe/RecipeStep.jsx
Labels: enhancement

#21 feat: #20 보유 식재료 등록 및 가져오기
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/layout/Layout.jsx
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeAdd.jsx
Labels: enhancement

#25 fix: #24 나의 냉장고 디자인
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeAdd.jsx
Labels: enhancement

#26 feat:#9 Header Search box Design
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#28 feat:#14 BoardEdit Page Design
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
Labels: enhancement

#29 feat:#14 BoardEdit Page navigate
  src/layout/Layout.jsx
Labels: enhancement

#31 feat:#30 Board Listup
  src/pages/board/Board.jsx
Labels: enhancement

#33 Fridge
  src/layout/Layout.jsx
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeDelete.jsx
Labels: enhancement

#34 fix: #32 FridgeAdd, FridgeDelete update
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeDelete.jsx
Labels: enhancement

#35 feat:#30 board & boardDetails Linked
  package-lock.json
  package.json
  src/App.js
  src/pages/board/Board.jsx
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#36 fix: #32 FridgeAdd, FridgeDelete date
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeDelete.jsx
Labels: enhancement

#37 feat:#30 board filter sort setting
  src/pages/board/Board.jsx
  src/pages/board/BoardDetails.jsx
Labels: enhancement

#39 feat:#38 Login,Signup 기능 구현
  package-lock.json
  src/layout/Layout.jsx
  src/pages/login/Login.jsx
  src/pages/login/signup.jsx
Labels: enhancement

#40 feat:#30 Board Like And Post/Get Dev
  package-lock.json
  src/layout/Layout.jsx
  src/pages/board/Board.jsx
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
Labels: bug, enhancement

#48 feat:#45 Logout 기능 구현
  src/App.js
  src/layout/Layout.jsx
  src/pages/board/Board.jsx
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
  src/pages/fridge/Fridge.jsx
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeDelete.jsx
  src/pages/login/Login.jsx
  src/pages/login/LogoutButton.jsx
Labels: enhancement

#50 feat: #49 메뉴 리스트 구현
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#53 fix:#45 로그아웃 버튼
  .idea/.gitignore
  .idea/frontend.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/layout/Layout.jsx
Labels: enhancement

#55 feat: #49 메뉴 레시피 구현
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#58 feat:#30 board image S3 connect
  src/pages/board/BoardDetails.jsx
  src/pages/board/BoardEdit.jsx
Labels: bug, enhancement

#60 feat:#59 Sign up UI 다듬기
  .idea/material_theme_project_new.xml
  src/pages/login/signup.jsx
  src/resources/icon/logo.png
Labels: enhancement

#64 Feat/recipe Recipe Page Like dev
  src/pages/board/BoardDetails.jsx
  src/pages/recipe/RecipeDetails.jsx
Labels: bug, enhancement

#65 feat:#63 Recipe Like status Read dev
  src/pages/board/BoardDetails.jsx
  src/pages/recipe/RecipeDetails.jsx
Labels: enhancement

#68 fix: #66 소비기한 달력으로 변경
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeUpdate.jsx
Labels: enhancement

#70 feat:#69 마이페이지 페이지 구현 및 로그아웃 버튼 위치 수정
  src/App.js
  src/layout/Layout.jsx
  src/pages/login/Login.jsx
  src/pages/login/signup.jsx
  src/pages/menu/Menu.jsx
  src/pages/menu/MyPage.jsx
Labels: enhancement

#71 fix: #49 미보유 재료 적은순 정렬
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#72 fix: #69 냉장고 초기화
  src/pages/menu/MyPage.jsx
Labels: enhancement

#73 feat:#7 페이지에 따른 버튼 노출 설정 및 자식/부모 데이터 전달
  src/layout/Layout.jsx
  src/pages/board/BoardDetails.jsx
Labels: bug, enhancement

#75 fix: #49 좋아요 목록 정렬
  src/pages/recipe/Recipe.jsx
  src/pages/recipe/RecipeDetails.jsx
Labels: enhancement

#77 fix:#7 Layout 하단 수정
  src/layout/Layout.jsx
Labels: enhancement

#78 fix: #49 메뉴 스크롤 수정
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#79 fix: #49 MemberFood 수정
  src/pages/fridge/FridgeUpdate.jsx
Labels: enhancement

#80 fix:#63 이미지 불러오기 버그 수정
  src/pages/recipe/RecipeDetails.jsx
Labels: bug

#84 feat:#83 회원 탈퇴 기능 구현
  src/pages/menu/MyPage.jsx
Labels: enhancement

#85 fix: #49 냉장고 아이콘 색 변경
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#88 feat:#30 좋아요 리스트 추가
  src/pages/board/Board.jsx
Labels: enhancement

#90 fix: #49 레시피 목록 조회
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#92 feat:#91 비밀번호 변경 기능 구현
  src/App.js
  src/pages/menu/ChangePassword.jsx
  src/pages/menu/MyPage.jsx
Labels: enhancement

#94 feat:#30 board 검색 및 Scroll 기능 구현
  src/pages/board/Board.jsx
Labels: enhancement

#95 fix: #43 메뉴 단일 조회 수정
  src/pages/recipe/RecipeDetails.jsx
Labels: enhancement

#96 design:#1 전체적인 폰트 설정
  src/App.css
  src/font.css
  src/index.css
  src/index.js
  src/layout/Layout.jsx
  src/pages/login/Login.jsx
Labels: bug, enhancement

#98 feat:#97 로그인 엔터기능 구현
  src/pages/login/Login.jsx
Labels: enhancement

#100 feat:#99 RecipeStep창에서 완료 시 통계 정보 저장
  src/pages/recipe/RecipeStep.jsx
Labels: enhancement

#101 feat:#99 통계 창 design
  src/App.js
  src/pages/menu/FridgeStatistics.jsx
  src/pages/menu/MyPage.jsx
Labels: enhancement

#102 fix: #20 식재료 등록 수정
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeUpdate.jsx
  src/pages/recipe/RecipeDetails.jsx
Labels: enhancement

#103 fix: #69 마이페이지 수정
  src/pages/menu/MyPage.jsx
Labels: enhancement

#104 fix: #22 식재료 등록, 수정 변경
  src/pages/fridge/FridgeAdd.jsx
  src/pages/fridge/FridgeUpdate.jsx
Labels: enhancement

#106 feat:#105 닉네임 변경 기능 구현
  src/App.js
  src/pages/menu/ChangeNickname.jsx
  src/pages/menu/ChangePassword.jsx
  src/pages/menu/MyPage.jsx
Labels: enhancement

#109 feat:#45 로그아웃 확인 모달 추가
  src/pages/menu/MyPage.jsx
Labels: enhancement

#110 fix: #43 냉장고 검색 수정
  src/pages/fridge/Fridge.jsx
Labels: enhancement

#111 feat:#97 엔터기능 구현 추가:냉장고,레시피
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#112 fix: #20 빈문자 검색
  src/pages/fridge/Fridge.jsx
Labels: enhancement

#113 fix: #43 냉장고 검색 수정
  src/pages/fridge/Fridge.jsx
Labels: enhancement

#114 fix: #49 빈칸 검색
  src/pages/fridge/Fridge.jsx
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#115 feat:#99 통계창 fridge & recipe 구현
  package-lock.json
  package.json
  src/App.js
  src/pages/menu/FridgeStatistics.jsx
  src/pages/menu/RecipeStatistics.jsx
Labels: bug, enhancement

#116 feat:#99 통계창 완성
  package-lock.json
  src/App.js
  src/GlobalStyle.js
  src/component/NumberCounter.jsx
  src/font.css
  src/pages/menu/FridgeStatistics.jsx
  src/pages/menu/RecipeStatistics.jsx
Labels: enhancement

#117 feat:#99 통계창 완성
  src/font.css
  src/pages/menu/RecipeStatistics.jsx
Labels: enhancement

#119 feat: #118 알레르기 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/layout/Layout.jsx
  src/pages/fridge/FridgeDelete.jsx
  src/pages/menu/AllergyFoods.jsx
  src/pages/menu/AllergyFoodsAdd.jsx
  src/pages/menu/AllergyFoodsDelete.jsx
  src/pages/menu/MyPage.jsx
  src/resources/icon/allergy_minus.png
  src/resources/icon/allergy_plus.png
Labels: enhancement

#120 fix:#99 점수 계산 오류 수정
  src/pages/login/signup.jsx
  src/pages/menu/FridgeStatistics.jsx
  src/pages/menu/RecipeStatistics.jsx
Labels: bug

#121 fix: #49 레시피 좋아요 조회 수정
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#123 feat: #122 추천레시피 구현
  src/App.js
  src/layout/Layout.jsx
  src/pages/recipe/RecommendedRecipe.jsx
  src/resources/icon/recommended.png
Labels: enhancement

#124 fix: #49 레시피 수정
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#125 fix: #122 레시피 수정
  src/pages/recipe/Recipe.jsx
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#126 feat:#99 버그 수정
  src/pages/login/signup.jsx
  src/pages/menu/RecipeStatistics.jsx
Labels: bug

#128 feat: #127 추천 레시피
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#129 fix: #127 추천 레시피 수정
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#130 fix: #49 레시피 수정
  src/pages/recipe/Recipe.jsx
Labels: enhancement

#135 Recipe recommend
  src/App.js
  src/layout/Layout.jsx
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#136 fix: #127 수정
  src/layout/Layout.jsx
Labels: enhancement

#137 fix: #149 추천레시피 수정
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#138 fix: #149 추천 레시피 수정
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#139 fix: #149 추천 레시피 수정
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement

#140 fix:69 마이페이지 수정
  package-lock.json
  src/pages/menu/MyPage.jsx
Labels: enhancement

#141 fix: #127 추천 레시피 수정
  src/pages/recipe/RecommendedRecipe.jsx
Labels: enhancement
